In [18]:
# Bag of words (BoW)

from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "I love NLP",
    "NLP is amazing",
    "I love learning NLP"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(corpus)

print("Vocabulary:", vectorizer.vocabulary_)
print("Bag of words represemntation:\n", X.toarray())

Vocabulary: {'love': 3, 'nlp': 4, 'is': 1, 'amazing': 0, 'learning': 2}
Bag of words represemntation:
 [[0 0 0 1 1]
 [1 1 0 0 1]
 [0 0 1 1 1]]


In [20]:
# TF-IDF using scikit learn

from sklearn.feature_extraction.text import TfidfVectorizer

tf_corpus = [
    "NLP is amazng and exciting",
    "I love studying NLP and working on NLP projects",
    "Machine learning includes NLP and other fields"
]

vectorizer =  TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(tf_corpus)

print("Vocabulary:", vectorizer.vocabulary_)

# Display he TF_IDF matrix in array format
print("TF-IDF Matrix\n", tfidf_matrix.toarray())


Vocabulary: {'nlp': 9, 'is': 5, 'amazng': 0, 'and': 1, 'exciting': 2, 'love': 7, 'studying': 13, 'working': 14, 'on': 10, 'projects': 12, 'machine': 8, 'learning': 6, 'includes': 4, 'other': 11, 'fields': 3}
TF-IDF Matrix
 [[0.52004008 0.30714405 0.52004008 0.         0.         0.52004008
  0.         0.         0.         0.30714405 0.         0.
  0.         0.         0.        ]
 [0.         0.22742704 0.         0.         0.         0.
  0.         0.38506745 0.         0.45485408 0.38506745 0.
  0.38506745 0.38506745 0.38506745]
 [0.         0.24743277 0.         0.4189401  0.4189401  0.
  0.4189401  0.         0.4189401  0.24743277 0.         0.4189401
  0.         0.         0.        ]]


In [21]:
# Word Embeddings - Word2Vec (requires gensim)

from gensim.models import Word2Vec
from gensim.models.word2vec import Text8Corpus
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Sample corpus
corpus = [
    ["cat", "sat", "on", "the", "mat"],
    ["dog", "barked", "at", "the", "cat"],
    ["the", "dog", "sat", "on", "the", "mat"],
    ["cats", "and", "dogs", "are", "friends"],
    ["dogs", "chase", "cats"]
]

# Train the Word2Vec model

model = Word2Vec(sentences=corpus, vector_size=50, window=2, min_count=1, sg=1)

print("Vocabulary:", list(model.wv.index_to_key))

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject